openapi: 3.0.1
info:
  title: api-wide-base-path
  version: ''
paths:
  /test/{pathParam}/{serviceParam}/{endpointParam}/{resourceParam}:
    post:
      operationId: service_post
      tags:
        - Service
      parameters:
        - name: pathParam
          in: path
          required: true
          schema:
            type: string
        - name: serviceParam
          in: path
          required: true
          schema:
            type: string
        - name: endpointParam
          in: path
          required: true
          schema:
            type: integer
        - name: resourceParam
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: ''
components:
  schemas: {}
  securitySchemes: {}
