name: ci

on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v4

      - name: Compile
        run: go build ./...
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v4

      - name: Setup wiremock server
        run: |
          PROJECT_NAME="wiremock-$(basename $(dirname $(pwd)) | tr -d '.')"
          echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV
          if [ -f wiremock/docker-compose.test.yml ]; then
            docker compose -p "$PROJECT_NAME" -f wiremock/docker-compose.test.yml down
            docker compose -p "$PROJECT_NAME" -f wiremock/docker-compose.test.yml up -d
            WIREMOCK_PORT=$(docker compose -p "$PROJECT_NAME" -f wiremock/docker-compose.test.yml port wiremock 8080 | cut -d: -f2)
            echo "WIREMOCK_PORT=$WIREMOCK_PORT" >> $GITHUB_ENV
          fi

      - name: Test
        run: go test ./...

      - name: Teardown wiremock server
        if: always()
        run: |
          if [ -f wiremock/docker-compose.test.yml ]; then
            docker compose -p "$PROJECT_NAME" -f wiremock/docker-compose.test.yml down
          fi
