# yaml-language-server: $schema=https://raw.githubusercontent.com/fern-api/fern/main/fern.schema.json
types:
  User:
    properties:
      id:
        type: string
      name:
        type: string

service:
  auth: false
  base-path: /api
  endpoints:
    getUsers:
      method: GET
      path: /users
      request:
        name: GetUsersRequest
        body:
          properties:
            sort: optional<string>
        headers:
          X-API-Version: string
      response: list<User>
