service:
  auth: false
  base-path: /
  endpoints:
    post:
      path: "/{endpointParam}"
      path-parameters:
        endpointParam: $rootVariable
      method: POST
      examples:
        - root-path-parameters:
            rootVariable: "test-value"
          response:
            body: null
