service:
  auth: false
  base-path: ""
  endpoints:
    upload:
      path: /upload-content
      method: POST
      request:
        content-type: "application/octet-stream"
        body: bytes
    
    download:
      path: /download-content
      method: GET
      response:
        type: bytes