openapi: 3.0.1
info:
  title: variables
  version: ''
paths:
  /{endpointParam}:
    post:
      operationId: service_post
      tags:
        - Service
      parameters:
        - name: endpointParam
          in: path
          required: true
          schema:
            type: string
          example: endpointParam
          examples:
            Example1:
              value: endpointParam
      responses:
        '204':
          description: ''
components:
  schemas: {}
  securitySchemes: {}
