openapi: 3.0.1
info:
  title: path-parameters
  version: ''
paths:
  /{tenant_id}/organizations/{organization_id}/:
    get:
      operationId: organizations_getOrganization
      tags:
        - Organizations
      parameters:
        - name: tenant_id
          in: path
          required: true
          schema:
            type: string
        - name: organization_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
  /{tenant_id}/organizations/{organization_id}/users/{user_id}:
    get:
      operationId: organizations_getOrganizationUser
      tags:
        - Organizations
      parameters:
        - name: tenant_id
          in: path
          required: true
          schema:
            type: string
        - name: organization_id
          in: path
          required: true
          schema:
            type: string
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /{tenant_id}/organizations/{organization_id}/search:
    get:
      operationId: organizations_searchOrganizations
      tags:
        - Organizations
      parameters:
        - name: tenant_id
          in: path
          required: true
          schema:
            type: string
        - name: organization_id
          in: path
          required: true
          schema:
            type: string
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            nullable: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Organization'
  /{tenant_id}/user/{user_id}:
    get:
      operationId: user_getUser
      tags:
        - User
      parameters:
        - name: tenant_id
          in: path
          required: true
          schema:
            type: string
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    patch:
      operationId: user_updateUser
      tags:
        - User
      parameters:
        - name: tenant_id
          in: path
          required: true
          schema:
            type: string
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
  /{tenant_id}/user/:
    post:
      operationId: user_createUser
      tags:
        - User
      parameters:
        - name: tenant_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
  /{tenant_id}/user/{user_id}/search:
    get:
      operationId: user_searchUsers
      tags:
        - User
      parameters:
        - name: tenant_id
          in: path
          required: true
          schema:
            type: string
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            nullable: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /{tenant_id}/user/{user_id}/metadata/v{version}:
    get:
      description: Test endpoint with path parameter that has a text prefix (v{version})
      operationId: user_getUserMetadata
      tags:
        - User
      parameters:
        - name: tenant_id
          in: path
          required: true
          schema:
            type: string
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: version
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /{tenant_id}/user/{user_id}/specifics/{version}/{thought}:
    get:
      description: >-
        Test endpoint with path parameters listed in different order than found
        in path
      operationId: user_getUserSpecifics
      tags:
        - User
      parameters:
        - name: tenant_id
          in: path
          required: true
          schema:
            type: string
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: version
          in: path
          required: true
          schema:
            type: integer
        - name: thought
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    Organization:
      title: Organization
      type: object
      properties:
        name:
          type: string
        tags:
          type: array
          items:
            type: string
      required:
        - name
        - tags
    User:
      title: User
      type: object
      properties:
        name:
          type: string
        tags:
          type: array
          items:
            type: string
      required:
        - name
        - tags
  securitySchemes: {}
