types:
  User:
    properties:
      id: string
      name: string

service:
  auth: false
  base-path: /users
  endpoints:
    getUser:
      method: GET
      path: /{userId}
      path-parameters:
        userId: string
      response: User
