# yaml-language-server: $schema=https://raw.githubusercontent.com/fern-api/fern/main/fern.schema.json

imports:
  folderBCommons: ../folder-b/common.yml

service:
  auth: false
  audiences:
    - public
  base-path: /
  endpoints:
    getDirectThread:
      path: ""
      method: GET
      request:
        name: GetDirectThreadRequest
        query-parameters:
          ids:
            type: string
            allow-multiple: true
          tags:
            type: string
            allow-multiple: true
      response: Response

types:
  Response:
    properties:
      foo: optional<folderBCommons.Foo>
