openapi: 3.0.1
info:
  title: Required nullable example
  version: ''
paths:
  /foo:
    get:
      operationId: getFoo
      tags:
        - ''
      parameters:
        - name: optional_baz
          in: query
          description: An optional baz
          required: false
          schema:
            type: string
            nullable: true
        - name: optional_nullable_baz
          in: query
          description: An optional baz
          required: false
          schema:
            type: string
            nullable: true
        - name: required_baz
          in: query
          description: A required baz
          required: true
          schema:
            type: string
          example: required_baz
          examples:
            Example1:
              value: required_baz
        - name: required_nullable_baz
          in: query
          description: A required baz
          required: false
          schema:
            type: string
            nullable: true
          example: required_nullable_baz
          examples:
            Example1:
              value: required_nullable_baz
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foo'
              examples:
                Example1:
                  value:
                    bar: bar
                    nullable_bar: nullable_bar
                    nullable_required_bar: nullable_required_bar
                    required_bar: required_bar
      summary: Get foo
  /foo/{id}:
    patch:
      operationId: updateFoo
      tags:
        - ''
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: X-Idempotency-Key
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foo'
      summary: Update foo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nullable_text:
                  type: string
                  nullable: true
                  description: Can be explicitly set to null to clear the value
                nullable_number:
                  type: number
                  format: double
                  nullable: true
                  description: Can be explicitly set to null to clear the value
                non_nullable_text:
                  type: string
                  nullable: true
                  description: Regular non-nullable field
components:
  schemas:
    Foo:
      title: Foo
      type: object
      properties:
        bar:
          type: string
          nullable: true
        nullable_bar:
          type: string
          nullable: true
        nullable_required_bar:
          type: string
          nullable: true
        required_bar:
          type: string
          example: required_bar
      required:
        - required_bar
  securitySchemes: {}
