name: ci

on: [push]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - uses: actions/checkout@master

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x

      - name: Print .NET info
        run: dotnet --info

      - name: Install tools
        run: dotnet tool restore

      - name: Restore dependencies
        run: dotnet restore src/SeedStreaming

      - name: Build Release
        run: dotnet build src/SeedStreaming -c Release --no-restore

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x

      - name: Print .NET info
        run: dotnet --info

      - name: Install tools
        run: |
          dotnet tool restore

      - name: Restore dependencies
        run: dotnet restore src

      - name: Build Release
        run: dotnet build src -c Release --no-restore

      - name: Run Tests
        run: dotnet test src -c Release --no-build --no-restore


  publish:
    needs: [compile]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x

      - name: Print .NET info
        run: dotnet --info

      - name: Install tools
        run: dotnet tool restore

      - name: Restore dependencies
        run: dotnet restore src/SeedStreaming

      - name: Build Release
        run: dotnet build src/SeedStreaming -c Release --no-restore

      - name: Publish
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_TOKEN }}
        run: |
          dotnet pack src/SeedStreaming -c Release --no-build --no-restore
          dotnet nuget push src/SeedStreaming/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source "nuget.org"

