name: ci

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        run: poetry install

      - name: Type check
        run: poetry run mypy

      - name: pre-commit
        run: poetry run pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        run: poetry install

      - name: Unit Test
        run: poetry run pytest -sv

  seed-sdk-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3

      - name: Install Seed
        run: npm install -g @fern-api/seed-cli@0.15.16

      - name: Seed Test
        run: seed test --workspace sdk --parallel 8

      - name: Ensure no changes to git-tracked files
        run: git --no-pager diff --exit-code

  seed-pydantic-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        run: poetry install

      - name: Install Seed
        run: npm install -g @fern-api/seed-cli@0.15.16

      - name: Seed Test
        run: seed test --workspace pydantic --parallel 6

      - name: Ensure no changes to git-tracked files
        run: git --no-pager diff --exit-code

  seed-fastapi-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        run: poetry install

      - name: Install Seed
        run: npm install -g @fern-api/seed-cli@0.15.16

      - name: Seed Test
        run: seed test --workspace fastapi --parallel 6

      - name: Ensure no changes to git-tracked files
        run: git --no-pager diff --exit-code
