name: Dependabot

on:
  pull_request:
    paths-ignore:
      - 'fern/docs/**'
      - 'fern/docs.yml'

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        if: ${{contains(steps.metadata.outputs.update-type, 'version-update')}}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Approve PR
        if: ${{contains(steps.metadata.outputs.update-type, 'version-update')}}
        uses: ./.github/actions/auto-approve
        with:
          approver-gh-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{github.event.pull_request.number}}    
          enforce-checks: 'true'
