name: IR Validation

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "packages/ir-sdk/fern/apis/**"
    branches:
      - main
  push:
    paths:
      - "packages/ir-sdk/fern/apis/**"
    branches:
      - main

jobs:
  run:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Install Fern
        run: npm install -g fern-api

      - name: Check IR Definitions
        run: |
          cd packages/ir-sdk
          fern check

      - name: Check IR Definitions
        env:
          FERN_TOKEN: dummy
        run: |
          cd packages/ir-sdk
          pnpm generate

      - name: Ensure no changes to git-tracked files
        run: git --no-pager diff --exit-code
