name: publish-generators

on:
  push:
    branches:
      - main
    paths:
      - "generators/openapi/VERSION"
      - "generators/python/sdk/VERSION"
      - "generators/python/fastapi/VERSION"
      - "generators/python/pydantic/VERSION"
      - "generators/postman/VERSION"
      - "generators/ruby/model/VERSION"
      - "generators/ruby/sdk/VERSION"
  workflow_dispatch:
    inputs:
      generator:
        description: "The generator to publish a dev release for"
        required: true
        type: choice
        options:
          - ruby-sdk
          - ruby-model

jobs:
  versions-changed:
    runs-on: ubuntu-latest
    outputs:
      openapi: ${{ steps.filter.outputs.openapi }}
      python-sdk: ${{ steps.filter.outputs.python-sdk }}
      fastapi: ${{ steps.filter.outputs.fastapi }}
      pydantic: ${{ steps.filter.outputs.pydantic }}
      postman: ${{ steps.filter.outputs.postman }}
      ruby-model: ${{ steps.filter.outputs.ruby-model }}
      ruby-sdk: ${{ steps.filter.outputs.ruby-sdk }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            openapi: 'generators/openapi/VERSION'
            python-sdk: 'generators/python/sdk/VERSION'
            fastapi: 'generators/python/fastapi/VERSION'
            pydantic: 'generators/python/pydantic/VERSION'
            postman: 'generators/postman/VERSION'
            ruby-model: 'generators/ruby/model/VERSION'
            ruby-sdk: 'generators/ruby/sdk/VERSION'

  pydantic-model:
    runs-on: ubuntu-latest
    needs: versions-changed
    if: ${{ needs.versions-changed.outputs.pydantic == 'true'}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install
        working-directory: ./generators/python
        run: poetry install

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fernapi
          password: ${{ secrets.FERN_API_DOCKERHUB_PASSWORD }}

      - name: Print Version
        run: |
          projectVersion=$(cat generators/python/pydantic/VERSION)
          echo $projectVersion
          echo "VERSION=$projectVersion" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./generators/python
          file: ./generators/python/pydantic/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: fernapi/fern-pydantic-model:${{env.VERSION}}

  fastapi:
    runs-on: ubuntu-latest
    needs: versions-changed
    if: ${{ needs.versions-changed.outputs.fastapi == 'true'}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install
        working-directory: ./generators/python
        run: poetry install

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fernapi
          password: ${{ secrets.FERN_API_DOCKERHUB_PASSWORD }}

      - name: Print Version
        run: |
          projectVersion=$(cat generators/python/fastapi/VERSION)
          echo $projectVersion
          echo "VERSION=$projectVersion" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./generators/python
          file: ./generators/python/fastapi/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: fernapi/fern-fastapi-server:${{env.VERSION}}

  python-sdk:
    runs-on: ubuntu-latest
    needs: versions-changed
    if: ${{ needs.versions-changed.outputs.python-sdk == 'true'}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install
        working-directory: ./generators/python
        run: poetry install

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fernapi
          password: ${{ secrets.FERN_API_DOCKERHUB_PASSWORD }}

      - name: Print Version
        run: |
          projectVersion=$(cat generators/python/sdk/VERSION)
          echo $projectVersion
          echo "VERSION=$projectVersion" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./generators/python
          file: ./generators/python/sdk/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: fernapi/fern-python-sdk:${{env.VERSION}}

  openapi:
    runs-on: ubuntu-latest
    needs: versions-changed
    if: ${{ needs.versions-changed.outputs.openapi == 'true'}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install
        run: yarn install

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fernapi
          password: ${{ secrets.FERN_API_DOCKERHUB_PASSWORD }}

      - name: Build CLI
        working-directory: ./generators/openapi
        run: yarn dist:cli

      - name: Print Version
        run: |
          projectVersion=$(cat generators/openapi/VERSION)
          echo $projectVersion
          echo "VERSION=$projectVersion" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./generators/openapi
          file: ./generators/openapi/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: fernapi/fern-openapi:${{env.VERSION}}

  postman:
    runs-on: ubuntu-latest
    needs: versions-changed
    if: ${{ needs.versions-changed.outputs.postman == 'true'}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install
        run: yarn install

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fernapi
          password: ${{ secrets.FERN_API_DOCKERHUB_PASSWORD }}

      - name: Build CLI
        working-directory: ./generators/postman
        run: yarn dist:cli

      - name: Print Version
        run: |
          projectVersion=$(cat generators/postman/VERSION)
          echo $projectVersion
          echo "VERSION=$projectVersion" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./generators/postman
          file: ./generators/postman/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: fernapi/fern-postman:${{env.VERSION}}

  ruby-model:
    runs-on: ubuntu-latest
    needs: versions-changed
    if: ${{ needs.versions-changed.outputs.ruby-model == 'true' || inputs.generator == 'ruby-model' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fernapi
          password: ${{ secrets.FERN_API_DOCKERHUB_PASSWORD }}

      - name: Install
        run: yarn install

      - name: Build CLI
        working-directory: ./generators/ruby/model
        run: yarn dist:cli

      - name: Print Version
        if: ${{ inputs.generator != 'ruby-model' }}
        run: |
          projectVersion=$(cat generators/ruby/model/VERSION)
          echo $projectVersion
          echo "VERSION=$projectVersion" >> $GITHUB_ENV

      - name: Print Version Dev
        if: ${{ inputs.generator == 'ruby-model' }}
        run: |
          projectVersion=$(cat generators/ruby/sdk/VERSION)
          commitNumber=$(git log --oneline | wc -l )
          echo $projectVersion-$commitNumber
          echo "VERSION=$projectVersion-$commitNumber" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./generators/ruby/model/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: fernapi/fern-ruby-model:${{env.VERSION}}

  ruby-sdk:
    runs-on: ubuntu-latest
    needs: versions-changed
    if: ${{ needs.versions-changed.outputs.ruby-sdk == 'true' || inputs.generator == 'ruby-sdk' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fernapi
          password: ${{ secrets.FERN_API_DOCKERHUB_PASSWORD }}

      - name: Install
        run: yarn install

      - name: Build CLI
        working-directory: ./generators/ruby/sdk
        run: yarn dist:cli

      - name: Print Version
        if: ${{ inputs.generator != 'ruby-sdk' }}
        run: |
          projectVersion=$(cat generators/ruby/sdk/VERSION)
          echo $projectVersion
          echo "VERSION=$projectVersion" >> $GITHUB_ENV

      - name: Print Version Dev
        if: ${{ inputs.generator == 'ruby-sdk' }}
        run: |
          projectVersion=$(cat generators/ruby/sdk/VERSION)
          commitNumber=$(git log --oneline | wc -l )
          echo $projectVersion-$commitNumber
          echo "VERSION=$projectVersion-$commitNumber" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./generators/ruby/sdk/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: fernapi/fern-ruby-sdk:${{env.VERSION}}
