name: Publish @fern-api/python-dynamic-snippets

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version of the library to publish."
        required: true
        type: string

env:
  PACKAGE_NAME: "@fern-api/python-dynamic-snippets"
  GITHUB_TOKEN: ${{ secrets.FERN_GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.FERN_NPM_TOKEN }}

jobs:
  run:
    runs-on: ubuntu-latest
    if: ${{ inputs.version != null }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: ðŸ“¥ Install
        uses: ./.github/actions/install

      - uses: bufbuild/buf-setup-action@v1.34.0
        with:
          github_token: ${{ github.token }}

      - uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Install protoc-gen-openapi
        run: go install github.com/fern-api/protoc-gen-openapi/cmd/protoc-gen-openapi@latest

      - name: ðŸ§ª Build
        run: pnpm --filter=${{ env.PACKAGE_NAME }} compile

      - name: ðŸ§ª Test
        run: pnpm --filter=${{ env.PACKAGE_NAME }} test

      - name: Publish @fern-api/python-dynamic-snippets
        run: |
          cd generators/python-v2/dynamic-snippets
          pnpm --filter=${{ env.PACKAGE_NAME }} dist ${{ inputs.version }}
          cd dist
          echo "//registry.npmjs.org/:_authToken=${{ env.NPM_TOKEN }}" > ~/.npmrc
          npm publish --access public

      - name: Update fern-platform dependency
        uses: ./.github/actions/update-fern-platform-dependency
        with:
          package-name: ${{ env.PACKAGE_NAME }}
          version: ${{ inputs.version }}
          github-token: ${{ secrets.FERN_GITHUB_TOKEN }}
