name: test-docs-generation

on:
  push:
    paths:
      - "fern/packages/cli/**"
      - "fern/packages/core/**"
      - "fern/packages/commons/**"
      - ".github/workflows/publish-docs.yml"
    branches:
      - main

jobs:
  run:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    if: github.event_name == 'push' && contains(github.ref, 'refs/heads/main')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Clone the Cohere Developer Experience repo
        run: |
          git clone https://github.com/cohere-ai/cohere-developer-experience.git
          echo "Cohere Developer Experience repo cloned successfully!"

      - name: Publish Docs
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_PROJECT_API_KEY }}
        run: |
          pnpm --filter @fern-api/cli dist:cli:prod
          cli_path="$(pwd)/packages/cli/cli/dist/prod/cli.cjs" 
          cd cohere-developer-experience
          sed -i 's/"organization": "[^"]*"/"organization": "fern"/' fern/fern.config.json
          sed -i 's/"version": "[^"]*"/"version": "*"/' fern/fern.config.json
          sed -i 's/^url:.*$/url: test-fern-cohere.docs.buildwithfern.com/' fern/docs.yml
          sed -i '/^customDomain:/d' fern/docs.yml
          pnpm install
          pnpm compile
          node $cli_path generate --docs --preview --log-level debug 