name: Write Changelogs to Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  copy-changelogs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch of fern repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install
        uses: ./.github/actions/install

      - name: Write generator changelogs
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: |
          echo "Generating changelogs for generators"
          pnpm seed:local generate changelog generator -o ./changelogs/ --clean-directory

      - name: Write CLI changelogs
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: |
          echo "Generating changelogs for CLI"
          pnpm seed:local generate changelog cli -o ./changelogs/cli/ --clean-directory

      - name: Checkout main branch of docs repo
        uses: actions/checkout@v4
        with:
          repository: fern-api/docs
          ref: main
          path: docs

      - name: update csharp-sdk changelog
        run: rsync -av --delete "changelogs/csharp-sdk/" "docs/fern/products/sdks/overview/csharp/changelog"

      - name: update go-sdk changelog
        run: rsync -av --delete "changelogs/go-sdk/" "docs/fern/products/sdks/overview/go/changelog"

      - name: update java-sdk changelog
        run: rsync -av --delete "changelogs/java-sdk/" "docs/fern/products/sdks/overview/java/changelog"

      - name: update php-sdk changelog
        run: rsync -av --delete "changelogs/php-sdk/" "docs/fern/products/sdks/overview/php/changelog"

      - name: update python-sdk changelog
        run: rsync -av --delete "changelogs/python-sdk/" "docs/fern/products/sdks/overview/python/changelog"

      - name: update ruby-sdk changelog
        run: rsync -av --delete "changelogs/ruby-sdk/" "docs/fern/products/sdks/overview/ruby/changelog"

      - name: update ts-sdk changelog
        run: rsync -av --delete "changelogs/ts-sdk/" "docs/fern/products/sdks/overview/typescript/changelog"

      - name: update rust-sdk changelog
        run: rsync -av --delete "changelogs/rust-sdk/" "docs/fern/products/sdks/overview/rust/changelog"

      - name: update swift-sdk changelog
        run: rsync -av --delete "changelogs/swift-sdk/" "docs/fern/products/sdks/overview/swift/changelog"

      - name: update cli changelog
        run: rsync -av --delete "changelogs/cli/" "docs/fern/products/cli-api-reference/cli-changelog"

      - name: create PR
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.FERN_GITHUB_PAT }}
          commit-message: "update changelogs"
          title: "Update changelogs from fern repo"
          branch: update-changelogs
          delete-branch: true
          path: docs

      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.FERN_GITHUB_PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          repository: fern-api/docs
          merge-method: squash

      - name: Approve PR
        if: steps.cpr.outputs.pull-request-operation == 'created'
        env:
          GH_TOKEN: ${{ secrets.PR_BOT_GH_PAT }}
        run: gh pr review ${{ steps.cpr.outputs.pull-request-number }} --repo fern-api/docs --approve
